# Generated by Django 3.1.3 on 2020-12-10 11:55

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=60)),
                ('tutor_email', models.CharField(max_length=60)),
                ('tutor_bio', models.TextField()),
                ('tutor_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('tutor_location', models.CharField(max_length=60, null=True)),
                ('languages', models.ManyToManyField(to='Tutor.Language')),
                ('programming_experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.experience')),
            ],
        ),
    ]
